export const CATEGORIES_ARR = [
    "Diversão",
    "Desconstrair",
    "Tecnologia",
    "Esportes",
    "Música",
    "Cinema",
    "Literatura",
    "Ciência",
    "Saúde",
    "Educação",
    "Meio Ambiente",
    "História",
    "Política",
    "Economia",
    "Arte",
    "Culinária",
    "Moda",
    "Viagens",
    "Carreira",
    "Negócios",
    "Jogos",
    "Religião",
    "Filosofia",
    "Psicologia",
    "Fotografia",
    "Animais",
    "Astronomia",
    "Inovação"
  ];
  